---
ssl_certs_country: "US"
ssl_certs_locality: "New York"
ssl_certs_organization: "MSD"
ssl_certs_state: "New York"
ssl_certs_common_name: "{{ nginx_hostname }}"
ssl_certs_san_name: "{{ ssl_certs_common_name }}"
ssl_certs_email: "info@{{ nginx_hostname }}"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ ssl_certs_country }}/ST={{ ssl_certs_state }}/L={{ ssl_certs_locality }}/O={{ ssl_certs_organization }}/CN={{ ssl_certs_common_name }}"
ssl_certs_path: "/etc/ssl/certs/{{ ssl_certs_common_name }}"
ssl_certs_conf_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.conf"
ssl_certs_path_owner: "root"
ssl_certs_path_group: "root"
ssl_certs_privkey_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.key"
ssl_certs_cert_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.crt"
ssl_certs_csr_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.csr"
nginx_snippets_path: "/etc/nginx/snippets"
ssl_certs_mode: "0700"
ssl_certs_force_replace: yes
ssl_certs_generate_self_signed: true
ssl_certs_key_size: "2048"
